const themes = {
  normal: {
    name: "Normal",
    description: "Everyday Grade 2 spelling words",
    questions: [
      { clue: "A pet that says meow and purrs", answer: "cat" },
      { clue: "A tall plant with a trunk, branches, and leaves", answer: "tree" },
      { clue: "You wear this on your foot when you go outside", answer: "shoe" },
      { clue: "The bright star we see in the sky during the day", answer: "sun" },
      { clue: "You use this to eat soup or cereal", answer: "spoon" },
      { clue: "A bird that swims and says quack", answer: "duck" },
      { clue: "A building where a family can live", answer: "house" },
      { clue: "An animal that lives in water and has fins", answer: "fish" },
      { clue: "A piece of furniture made for one person to sit on", answer: "chair" },
      { clue: "Something with pages that you read", answer: "book" },
      { clue: "A pet that barks and wags its tail", answer: "dog" },
      { clue: "An animal with feathers, wings, and a beak", answer: "bird" },
      { clue: "A round toy you can throw, catch, or kick", answer: "ball" },
      { clue: "A vehicle with four wheels that drives on roads", answer: "car" },
      { clue: "Soft white flakes that fall from the sky in winter", answer: "snow" },
      { clue: "Drops of water that fall from clouds", answer: "rain" },
      { clue: "Clothing you wear over your clothes to stay warm", answer: "coat" },
      { clue: "Something that tells you what time it is", answer: "clock" },
      { clue: "The colourful part of a plant that can smell nice", answer: "flower" },
      { clue: "A small animal that hops and says ribbit", answer: "frog" },
      { clue: "A large four-legged animal that people can ride", answer: "horse" },
      { clue: "A very small animal with a long tail that squeaks", answer: "mouse" },
      { clue: "A vehicle with wings that carries people through the sky", answer: "plane" },
      { clue: "An animal with long ears that hops", answer: "rabbit" },
      { clue: "A hard piece of stone you might find on the ground", answer: "rock" },
      { clue: "A long animal with no legs that slithers", answer: "snake" },
      { clue: "The large round object that travels around Earth", answer: "moon" },
      { clue: "A tiny point of light you can see in the night sky", answer: "star" },
      { clue: "A vehicle that travels on railway tracks", answer: "train" },
      { clue: "A large road vehicle used to carry heavy things", answer: "truck" },
      { clue: "A round fruit that can be red, green, or yellow", answer: "apple" },
      { clue: "A sweet baked food often eaten at birthdays", answer: "cake" },
      { clue: "A farm animal that says moo and gives milk", answer: "cow" },
      { clue: "You open this to enter or leave a room", answer: "door" },
      { clue: "A vehicle that carries people across water", answer: "boat" },
      { clue: "A toy on a string that flies in the wind", answer: "kite" },
      { clue: "A flat green part that grows on a plant or tree", answer: "leaf" },
      { clue: "Something you wear on your head", answer: "hat" },
      { clue: "A piece of furniture you sleep in", answer: "bed" },
      { clue: "A small container you drink from", answer: "cup" }
    ]
  },

  minecraft: {
    name: "Minecraft",
    description: "Minecraft mobs, blocks, tools, and exploring",
    questions: [
      { clue: "The Minecraft world is made of cubes called", answer: "blocks" },
      { clue: "A green hostile mob that sneaks up and explodes", answer: "creeper" },
      { clue: "A hostile mob that looks like a walking dead person", answer: "zombie" },
      { clue: "A hostile mob made of bones that shoots arrows", answer: "skeleton" },
      { clue: "An eight-legged mob that can climb walls", answer: "spider" },
      { clue: "You place this to make light inside a dark cave", answer: "torch" },
      { clue: "The tool you use to mine stone and ores", answer: "pickaxe" },
      { clue: "A weapon with a long blade used for fighting mobs", answer: "sword" },
      { clue: "A rare blue gem used to make strong tools and armour", answer: "diamond" },
      { clue: "A box used to store your items", answer: "chest" },
      { clue: "You sleep in this to skip the night and set your respawn point", answer: "bed" },
      { clue: "A place underground where you often find stone and ores", answer: "cave" },
      { clue: "A hot orange liquid that can burn you", answer: "lava" },
      { clue: "A blue liquid you can swim in and collect with a bucket", answer: "water" },
      { clue: "A brown block found underneath grass", answer: "dirt" },
      { clue: "The green block that covers much of the ground", answer: "grass" },
      { clue: "A pink farm animal that can be ridden with the right equipment", answer: "pig" },
      { clue: "A farm animal that gives leather and beef", answer: "cow" },
      { clue: "An animal that gives wool when you use shears on it", answer: "sheep" },
      { clue: "A tame animal that can follow you and help fight enemies", answer: "wolf" }
      { clue: "A tall black mob that can teleport and gets angry if you look at its face", answer: "enderman" },
      { clue: "A squishy green monster that hops around", answer: "slime" },
      { clue: "A tool used to chop wood faster", answer: "axe" },
      { clue: "A tool used to dig dirt, sand, and gravel faster", answer: "shovel" },
      { clue: "A place made of obsidian that lets you travel to the Nether", answer: "portal" },
      { clue: "A red dimension filled with lava, piglins, and dangerous mobs", answer: "nether" },
      { clue: "A flying hostile mob in the Nether that shoots fireballs", answer: "ghast" },
      { clue: "A block used to cook food and smelt ores", answer: "furnace" },
      { clue: "A red powder used to build simple machines and circuits", answer: "redstone" }
    ]
  }
};
